apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments-worker
  template:
    metadata:
      labels:
        app: payments-worker
    spec:
      containers:
      - name: payments-worker
        image: payments-worker:dev
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: payments-worker
  labels:
    app: payments-worker
spec:
  selector:
    app: payments-worker
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP